apps/client/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView

from . import views
from .api import view_sets
from rest_framework import routers


app_name = "client"

router = routers.DefaultRouter()
router.register(r"api/client", view_sets.AddClient)
router.register(r"api/contract", view_sets.ContractView)
# router.register(r"api/additional_contract", view_sets.AdditionalContractView)


urlpatterns = [
    path("", views.clients, name="client"),
    path("", include(router.urls)),
    # path("api/v1/clientlist/", ClientIpiView.as_view()),
    # path("", views.ClientView.as_view(), name="index"),
    # path("<int:client_id>", views.client, name="client"),
    # path("<int:client_id>/<slug:slug>", views.addContract, name="contract"),
    # path("<int:client_id>/<slug:slug>/sub", views.AddSubcontractors, name="sub"),
    # path("<int:client_id>/<slug:slug>/employee", views.add_employee, name="employee"),
    # path("<int:client_id>/<slug:slug>/adv", views.add_adv, name="adv"),
]

apps/core/urls.py
from django.urls import include, path



from . import views

# router.register(r'accounts', AccountViewSet)
app_name = 'core'

urlpatterns = [
    path("", views.index, name="home"),
    path("tech", views.tech, name="tech"),
    # path('api/', include((router.urls))),
    
]

apps/operation/urls.py
from django.urls import include, path
from django.views.generic.base import TemplateView

from . import views
from .api import view_sets
from rest_framework import routers


app_name = "operation"

router = routers.DefaultRouter()
# router.register(r"api/entry", view_sets.OperationEntryViews)
# router.register(r"api/out", view_sets.OperationOutViews)
router.register(r"api/operation", view_sets.OperationViews)
router.register(r"api/operation_oper_account", view_sets.OperationViews)
router.register(r"api/add-category-office", view_sets.CategoryOperationViews) 


urlpatterns = [

    path("", include(router.urls)),
    path("", views.index, name="index"),
    path("operation_inside", views.operation_inside, name="operation_inside"),
    path("oper_account", views.operation_inside_oper_account, name="oper_accaunt"),
    path("nalog", views.operation_inside_nalog, name="nalog"),

    path("salary", views.operation_inside_salary, name="salary"),
    
    path("operation_outside", views.operation_outside, name="operation_outside"),
    path("operation_storage", views.operation_storage, name="operation_storage"),

#     path("operation_outside/<slug:slug>", (views.operation_outside_categ),
#          name="operation_outside_categ"),
#     path("operation_inside/<slug:slug>", (views.operation_inside_categ),
#          name="operation_inside_categ"),


    # path("api/v1/clientlist/", ClientIpiView.as_view()),
    # path("", views.ClientView.as_view(), name="index"),
    # path("<int:client_id>", views.client, name="client"),
    # path("<int:client_id>/<slug:slug>", views.addContract, name="contract"),
    # path("<int:client_id>/<slug:slug>/sub", views.AddSubcontractors, name="sub"),
    # path("<int:client_id>/<slug:slug>/employee", views.add_employee, name="employee"),
    # path("<int:client_id>/<slug:slug>/adv", views.add_adv, name="adv"),
]

apps/service/urls.py
from django.urls import include, path

from . import views
from rest_framework import routers
from .api import view_sets
from django.views.decorators.cache import cache_page

app_name = "service"

router = routers.DefaultRouter()
router.register(r"api/service_category", view_sets.ServiceView)
router.register(r"api/month_bill", view_sets.ServicesMonthlyBillView)
router.register(r"api/subcontract-category-adv", view_sets.SubcontractCategoryAdvView)
router.register(r"api/subcontract-category-other", view_sets.SubcontractCategoryOtherView)
router.register(r"api/subcontract", view_sets.SubcontractMonthView)
# router.register(r"create-contract", views.CreateContract)
# basename="service"
# router.register(r'bill/client_list/', views.BillViewSet)


urlpatterns = [
    path("", views.index, name="index"),
     path("new_month", views.new_month, name="new_month"),
    # path("ADV", views.adv_index, name="adv"),
    # path("<int:client_id>", views.service_one, name="service_one"),
    path("", include(router.urls)),
    path("<slug:slug>",(views.service_one),name="service_one"),
    # path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]
# <int:client_id>/<slug:slug>

# path("<int:client_id>/<slug:slug>", views.addContract, name="contract"),

project/urls.py
# from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

# router = routers.DefaultRouter()

# router.registry.extend(client_router.registry)
# from . import views
urlpatterns = [
     path('__debug__/', include('debug_toolbar.urls')),
    path("admin/", admin.site.urls),
    
    path("", include("apps.core.urls", namespace="core")),
    path("service/", include("apps.service.urls", namespace="service")),
    path("clients/", include("apps.client.urls", namespace="clients")),
    path("employee/", include("apps.employee.urls", namespace="employees")),
    path("operations/", include("apps.operation.urls", namespace="operation")),
    # path("bank/", include("apps.bank.urls", namespace="bank")),
    path('api/', include('rest_framework.urls')),
    # path("apiV1/", include(router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/views.py
from django.http import HttpResponse
from django.shortcuts import render

from apps.service.models import Adv


def index(request):
    title = "Главная"
    context = {
        "title": title,

    }

    return render(request, "core/index.html", context)

def tech(request):

    title = "Тех.раздел"
    
    category_adv = Adv.objects.all()
    
    context = {
        "title": title,
        "tech_adv_category":category_adv,

    }

    return render(request, "core/tech.html", context)

  

apps/core/templates/core/includes/header_menu.html
<header class="header">
  <ul class="header_nav">
    <li class="header_nav-link">
      {% url 'service:index' as the_url %}
      {% if request.get_full_path == the_url or type_url ==  "service" %}
        <span class="menu-active">Услуги</span>
      {% else %}
        <a class="" href="{% url 'service:index' %}">Услуги</a>
      {% endif %}
    </li>

    <li class="header_nav-link">
      {% url 'operation:operation_outside' as the_url %}
      {% if request.get_full_path == the_url %}
        <span class="menu-active">Внешние счета</span>
      {% else %}
        <a class="" href="{% url 'operation:operation_outside' %}">Внешние счета</a>
      {% endif %}
    </li>

    <li class="header_nav-link">
      {% url 'operation:operation_inside' as the_url %}
      {% if request.get_full_path == the_url or type_url ==  "operation_inside" %}
        <span class="menu-active">Внутренние счета</span>
      {% else %}
        <a class="" href="{% url 'operation:operation_inside' %}">Внутренние счета</a>
      {% endif %}
    </li>

    <li class="header_nav-link">
      {% url 'operation:operation_storage' as the_url %}
      {% if request.get_full_path == the_url %}
        <span class="menu-active">Хранилище</span>
      {% else %}
        <a class="" href="{% url 'operation:operation_storage' %}">Хранилище</a>
      {% endif %}
    </li>
    <li class="header_nav-link">
      {% url 'clients:client' as the_url %}
      {% if request.get_full_path == the_url %}
        <span class="menu-active">Клиенты</span>
      {% else %}
        <a class="" href="{% url 'clients:client' %}">Клиенты</a>
      {% endif %}
    </li>
    {% comment %} <li class="header_nav-link">
        {% url 'core:home' as the_url %} 
        {% if request.get_full_path == the_url %}
        <span class="menu-active">Сотрудники</span> 
        {% else %}
        <a class="" href="{% url 'core:home' %}">Сотрудники</a>
        {% endif %} 
    </li> {% endcomment %}
    {% comment %} <li class="header_nav-link">
        {% url 'core:home' as the_url %} 
        {% if request.get_full_path == the_url %}
        <span class="menu-active"></span> 
        {% else %}
        <a class="" href="{% url 'core:home' %}">Сотрудники</a>
        {% endif %} 
    </li>  {% endcomment %}
  </ul>
  <ul class="header_nav_tech">
    <li class="header_nav-link">
      {% url 'core:tech' as the_url %}
      {% if request.get_full_path == the_url %}
        <span class="menu-active">Тех.раздел</span>
      {% else %}
        <a class="" href="{% url 'core:tech' %}">Тех.раздел</a>
      {% endif %}
    </li>
  </ul>
</nav>
</header>

apps/core/templates/core/includes/scripts.html
{% load static %}

<!--core  -->
<script src="{% static 'core/js/main.js' %}"></script>
<script src="{% static 'core/js/modal_add_category.js' %}"></script>

<!--клиенты  -->
<script src="{% static 'client/js/client.js' %}"></script>

<!--услуги  -->
<script src="{% static 'service/js/service.js' %}"></script>
<script src="{% static 'service/js/subcontract.js' %}"></script>
<script src="{% static 'service/js/incoming_operation_add.js' %}"></script>
<script src="{% static 'service/js/out_opetation.js' %}"></script>
<script src="{% static 'service/js/out_operation_suborder_people.js' %}"></script>
<script src="{% static 'service/js/service_sctipts.js' %}"></script>
<script src="{% static 'service/js/add_operation_storage.js' %}"></script>

<!--внутрение счета  -->
<!--оперсчет  -->
<script src="{% static 'operation/js/oper_account/modal_add_category_office.js' %}"></script>
<script src="{% static 'operation/js/oper_account/oper_account_scripts.js' %}"></script>
<script src="{% static 'operation/js/oper_account/modal_add_operation_oper_account.js' %}"></script>
<!--зарплаты  -->
<script src="{% static 'operation/js/salary/modal_add_employee.js' %}"></script>
<script src="{% static 'operation/js/salary/salary_scripts.js' %}"></script>
<script src="{% static 'operation/js/salary/add_operation_salary.js' %}"></script>

apps/core/templates/core/includes/stylesheets.html
{% load static %}

<link rel="stylesheet" href="{% static 'core/css/fonts.css' %}" />
<link rel="stylesheet" href="{% static 'core/css/reset.css' %}" />
<link rel="stylesheet" href="{% static 'core/css/global.css' %}" />
<link rel="stylesheet" href="{% static 'core/css/style.css' %}" />
<link rel="stylesheet" href="{% static 'core/css/media.css' %}" />